# Generated by Django 4.2.1 on 2023-05-31 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('important', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
